apiVersion: apps/v1
kind: Deployment
metadata: 
  name: studentapp
  labels:
    app: studentapp
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:  # Moved selector here
    matchLabels:
      app: studentapp
  template:
    metadata: 
      labels:
        app: studentapp          
    spec: 
      containers: 
        - name: student-container
          image: tomcat:latest
          resources: 
            requests:
              cpu: "25m"
              memory: "50Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP                      
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: studentapp
  labels:
    app: studentapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: studentapp
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 
