apiVersion: apps/v1 
kind: DaemonSet
metadata:
        name: daemonset
        labels: 
              app: daemonset
spec:
     selector:
           matchLabels:
                app: daemonset    
     template:
          metadata: 
              labels: 
                  app: daemonset 
          spec:
            containers:
                - name: mypod
                  image: nginx:latest       
                  ports:  
                    - name: http
                      containerPort: 80
                      protocol: TCP  
